### ISSUE TITLE
We could not find your user account - For old users

### ISSUE THREAD

**Issue by AvivMalka** [unosquare/passcore#187]
**Describe the bug**
I have a user I created 2 months ago, before I deployed PassCore - When I try to change his password, I get the following error:
We could not find your user account.
But if I create a new user in AD, there is no problem reseting his password.

**To Reproduce**
1. Tried to change an old user pass, not working
2. Created new user, changed his pass - now it works

**Expected behavior**
To change everyone password, no matter when the user has been created.

Version: PassCore v3.1.0

**Comment by unquietwiki** [comment]
@AvivMalka @bmeyer06 Hey guys, please indicate what OS' you're running Passcore on; as well as if you are relying on Active Directory, or LDAP. I know the latter is being worked on for improvements.

**Comment by bmeyer06** [comment]
I'm running it on Windows Server 2016 Datacenter. It's relying on Active Directory.

**Comment by unquietwiki** [comment]
@AvivMalka @bmeyer06 I think this can be a problem for old group policies, and/or an inability for the user to log into the server; #147 might be related.

**Comment by bmeyer06** [comment]
I don't see how that could be. I have a subset group of users that all perform the same function, are all members of the exact same security groups and user accounts all exist in the same OU, and the issue happens on ~25% of them (give or take).

On the server side, the new environment (which has the issue) is running 2016. The older environment (which works great for everyone) is running 2012 R2. They have the exact same GPOs applied and are in the same OU. So unless it's somehow something with the GPO that only affects server 2016 - but if that was the case I imagine that it would impact all users, not a subset.

**Comment by unquietwiki** [comment]
@bmeyer06 At my last job, where I deployed Passcore, I observed a behavior like you're describing with users that hadn't been active on the system in a while. Remote users may need to log in on the actual network itself, to get their AD profiles to update correctly. The company was also doing stringent password requirements.

**Comment by shethpriyank** [comment]
Hi I have installed successfully. I am able to browse. configured all required information. Now the problem is, when we try to change password it shows message "We could not find your user account" Pl. help here in diagnose the problem and resolve the same.

**Comment by AvivMalka** [comment]
@unquietwiki Windows 2012 R2 with Active Directory.

I still don't see anything on the logs.. Tried to reinstall it so many times - nada

**Comment by veinom** [comment]
I'm having this issue as well - "We could not find your user account"

I've updated the DefaultDomain in appsettings.json and have tried both our usual domain and our short domain names.  With the previous version I would append the domain in passwordcontroller.cs by doing model.Username += "@domain.com" , and it worked ... but domain.com doesn't work for the DefaultDomain. 

Is there any logging besides the IIS logging that can make it so that I can see the exact LDAP query that's being sent to our DC?    

Passcore is running on 2008R2 querying AD.

**Comment by zgariat** [comment]
Hi,

Same here, no errors in logs. It only works for new created users... Important to note that "old users" was created copying existing ones (for group membreship) with "password never expire" and now I want to use this website to force all to change their AD passwords. I have installed on multiple machines (including one DC) with same result.
Passcore running on Windows2016Server Standard (1607) querying AD.

Thank you

**Comment by geoperez** [comment]
Please check issue #221 

Closing this ticket.
