### ISSUE TITLE
Update password don't work

### ISSUE THREAD

**Issue by JeromeD49** [unosquare/passcore#260]
**PassCore Server**
- OS: [ Linux Debian 9]
- Provider: [Active Directory]
- Settings file (without sensitive information): 

{
  "Logging": {
    "IncludeScopes": true,
    "LogLevel": {
      "Default": "Debug",
      "System": "Debug",
      "Microsoft": "Debug"
    }
  },
  "WebSettings": {
    "EnableHttpsRedirect": false
  },
  "Kestrel": {
  "EndPoints": {
    "Http": {
      "Url": "http://XXXXX:5000"
    }
   }
   },
  "AppSettings": {
    // The following options for AD Provider (remove if you don't use this Provider)
    "UseAutomaticContext": false, // Set true to allow PassCore to reset password using the same credentials, or false if you will fill the credentials below
    "RestrictedADGroups": [
      "Administrators",
      "Domain Admins",
      "Enterprise Admins"
    ], // Set the AD groups to restrict the use of PassCore
    "AllowedADGroups": [ "" ], // Set the AD Groups to allow PassCore, if the array is empty all the groups no-restricted above are allowed
    "IdTypeForUser": "SAM", // Possible values are "DN", "GUID", "Name", "SAM", "SID" and "UPN" (Default UPN)
    "UpdateLastPassword": false, // Set true to allow PassCore to  update the last password timestamp
    // The following options are for LDAP Provider (remove if you don't use this Provider)
    "LdapSearchBase": "OU=XXXXX,DC=XXXXX,DC=XXXXX",
    "LdapStartTls": false,
    "LdapChangePasswordWithDelAdd": true,
    "LdapSearchFilter": "(sAMAccountName={Username})", // Another value: "(&(objectClass=person)(cn={Username}))"
    // General options (valid for both providers)
    "LdapHostnames": [ "XXXXX" ], // Set your hostname(s)
    "LdapPort": 389, // Default for AD is 389, for LDAPS 636
    "LdapUsername": "XXXXXXXX", // Set the username or distinguish name (DN) to bind the LDAP server
    "LdapPassword": "XXXXXXX", // Set the password for the username
    "DefaultDomain": "XXXXXXXX" // Set your default AD domain here, or non "@" logins will not work! Use empty value to allow user to set the domain. This option is ONLY available with UPN.
  },
  "ClientSettings": {
    "ValidationRegex": {
      "EmailRegex": "^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\\.[a-zA-Z0-9-]+)*$",
      "UsernameRegex": "^[a-zA-Z0-9._-]{3,20}$"
    },
    "ShowPasswordMeter": true,
    "Recaptcha": {
      "SiteKey": "", // ReCAPTCHA public key: replace this! or leave empty if you don't need ReCAPTCHA
      "PrivateKey": "", // ReCAPTCHA private key: replace this! or leave empty if you don't need ReCAPTCHA
      "LanguageCode": "fr"
    },
    "UseEmail": "false",
    "ApplicationTitle": "Passcore",
    "ChangePasswordTitle":  "Change Account Password",
    "ChangePasswordForm": {
      "HelpText": "If you are having trouble with this tool, please contact IT Support ",
      "UsernameLabel": "Username",
      "UsernameHelpblock": "Your organization's email address",
      "UsernameDefaultDomainHelperBlock": "Your organization's username",
      "CurrentPasswordLabel": "Current Password",
      "CurrentPasswordHelpblock": "Enter your current password",
      "NewPasswordLabel": "New Password",
      "NewPasswordHelpblock": "Enter a strong password.",
      "NewPasswordVerifyLabel": "Re-enter New Password",
      "NewPasswordVerifyHelpblock": "Enter your new password again",
      "ChangePasswordButtonLabel": "Change Password"
    },
    "ErrorsPasswordForm": {
      "FieldRequired": "This field is required",
      "UsernamePattern": "Please enter a valid username",
      "UsernameEmailPattern": "Please enter a valid email address",
      "PasswordMatch": "Passwords do not match"
    },
    "Alerts": {
      "SuccessAlertTitle": "You have changed your password successfully.",
      "SuccessAlertBody": "Please note it may take a few hours for your new password to reach all domain controllers.",
      "ErrorPasswordChangeNotAllowed": "You are not allowed to change your password. Please contact your system administrator.",
      "ErrorInvalidCredentials": "You need to provide the correct username / password.",
      "ErrorInvalidDomain": "You have supplied an invalid domain to logon to.",
      "ErrorInvalidUser": "We could not find your user account.",
      "ErrorCaptcha": "Could not verify you are not a robot",
      "ErrorFieldRequired": "Fulfill all the fields",
      "ErrorFieldMismatch": "The passwords do not match"
    }
  }
}

**Describe the bug**
When I try to update the password for a user I got this message : 

![image](https://user-images.githubusercontent.com/47627853/52777743-c73bb880-3044-11e9-8699-54193c8c4920.png)

In the logs I see this message : 

Feb 14 10:39:04 XXXXXXX[3366]:       Executing action method Unosquare.PassCore.Web.Controllers.PasswordController.Post (Unosquare.PassCore.Web) with arguments (Unosquare.PassCore.Web.Models.ChangePasswordModel) - Validation state: Valid
Feb 14 10:39:04 XXXXXXX[3366]: #033[40m#033[1m#033[33mwarn#033[39m#033[22m#033[49m: Zyborg.PassCore.PasswordProvider.LDAP.LdapPasswordChangeProvider[0]
Feb 14 10:39:04 XXXXXXX[3366]:       Unexpected Win32 API error; error code: 00002077 - LdapException: Unwilling To Perform (53) Unwilling To Perform
Feb 14 10:39:04 XXXXXXX[3366]:       LdapException: Server Message: 00002077: SvcErr: DSID-03190EBE, problem 5003 (WILL_NOT_PERFORM), data 0
Feb 14 10:39:04 XXXXXXX[3366]:
Feb 14 10:39:04 XXXXXXX[3366]:       LdapException: Matched DN:

If I set the parameter "LdapChangePasswordWithDelAdd" to false, Passcore tells me OK you have changed your password successfully, but the password don't change.

Thanks for your help

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by JeromeD49** [comment]
After research, error "LdapException: Server Message: 00002077: SvcErr: DSID-03190EBE, problem 5003 (WILL_NOT_PERFORM), data 0" comes from the protocol LDAP and no LDAPS : 

https://community.boomi.com/s/article/ldaperrorcode53

After change the parameter "LdapPort" to 636, I got this message : 

![image](https://user-images.githubusercontent.com/47627853/52800756-b444da80-307c-11e9-99a1-4348ecb7c316.png)

Feb 14 17:14:18 passcore: Failed to update password
Feb 14 17:14:18 passcore: System.ArgumentNullException: Value cannot be null.
Feb 14 17:14:18 passcore: Parameter name: input


Here is the full log : 

Feb 14 17:14:17 passcore: #033[40m#033[37mdbug#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Server.Kestrel[1]
Feb 14 17:14:17 passcore: Connection id "0HLKIISP52N9R" started.
Feb 14 17:14:17 passcore: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
Feb 14 17:14:17 passcore: Request starting HTTP/1.1 POST http://XXXXXXX:5000/api/password application/json 108
Feb 14 17:14:17 passcore: #033[40m#033[37mdbug#033[39m#033[22m#033[49m: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[1]
Feb 14 17:14:17 passcore: POST requests are not supported
Feb 14 17:14:17 passcore: #033[40m#033[37mdbug#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Routing.Tree.TreeRouter[1]
Feb 14 17:14:17 passcore: Request successfully matched the route with name '(null)' and template 'api/Password'
Feb 14 17:14:17 passcore: #033[40m#033[37mdbug#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Mvc.Internal.ActionSelector[2]
Feb 14 17:14:17 passcore: Action 'Unosquare.PassCore.Web.Controllers.PasswordController.Get (Unosquare.PassCore.Web)' with id '25d10aab-775b-458f-8e54-f46091a289c2' did not match the constraint 'Microsoft.AspNetCore.Mvc.Internal.HttpMethodActionConstraint'
Feb 14 17:14:17 passcore: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
Feb 14 17:14:17 passcore: Route matched with {action = "Post", controller = "Password"}. Executing action Unosquare.PassCore.Web.Controllers.PasswordController.Post (Unosquare.PassCore.Web)
Feb 14 17:14:17 passcore: #033[40m#033[37mdbug#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
Feb 14 17:14:17 passcore: Execution plan of authorization filters (in the following order): None
Feb 14 17:14:17 passcore: #033[40m#033[37mdbug#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
Feb 14 17:14:17 passcore: Execution plan of resource filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter
Feb 14 17:14:17 passcore: #033[40m#033[37mdbug#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
Feb 14 17:14:17 passcore: Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Internal.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000)
Feb 14 17:14:17 passcore: #033[40m#033[37mdbug#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
Feb 14 17:14:17 passcore: Execution plan of exception filters (in the following order): None
Feb 14 17:14:17 passcore: #033[40m#033[37mdbug#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
Feb 14 17:14:17 passcore: Execution plan of result filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter
Feb 14 17:14:17 passcore: #033[40m#033[37mdbug#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder[22]
Feb 14 17:14:17 passcore: Attempting to bind parameter 'model' of type 'Unosquare.PassCore.Web.Models.ChangePasswordModel' ...
Feb 14 17:14:17 passcore: #033[40m#033[37mdbug#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder[24]
Feb 14 17:14:17 passcore: Attempting to bind model of type 'Unosquare.PassCore.Web.Models.ChangePasswordModel' using the name '' in request data ...
Feb 14 17:14:17 passcore: #033[40m#033[37mdbug#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder[2]
Feb 14 17:14:17 passcore: Rejected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.JsonPatchInputFormatter' for content type 'application/json'.
Feb 14 17:14:17 passcore: #033[40m#033[37mdbug#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder[1]
Feb 14 17:14:17 passcore: Selected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.JsonInputFormatter' for content type 'application/json'.
Feb 14 17:14:17 passcore: #033[40m#033[37mdbug#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Server.Kestrel[25]
Feb 14 17:14:17 passcore: Connection id "0HLKIISP52N9R", Request id "0HLKIISP52N9R:00000001": started reading request body.
Feb 14 17:14:17 passcore: #033[40m#033[37mdbug#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Server.Kestrel[26]
Feb 14 17:14:17 passcore: Connection id "0HLKIISP52N9R", Request id "0HLKIISP52N9R:00000001": done reading request body.
Feb 14 17:14:17 passcore: #033[40m#033[37mdbug#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder[25]
Feb 14 17:14:17 passcore: Done attempting to bind model of type 'Unosquare.PassCore.Web.Models.ChangePasswordModel' using the name ''.
Feb 14 17:14:17 passcore: #033[40m#033[37mdbug#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder[23]
Feb 14 17:14:17 passcore: Done attempting to bind parameter 'model' of type 'Unosquare.PassCore.Web.Models.ChangePasswordModel'.
Feb 14 17:14:17 passcore: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
Feb 14 17:14:17 passcore: Executing action method Unosquare.PassCore.Web.Controllers.PasswordController.Post (Unosquare.PassCore.Web) with arguments (Unosquare.PassCore.Web.Models.ChangePasswordModel) - Validation state: Valid
Feb 14 17:14:18 passcore: #033[41m#033[30mfail#033[39m#033[22m#033[49m: Unosquare.PassCore.Web.Controllers.PasswordController[0]
Feb 14 17:14:18 passcore: Failed to update password
Feb 14 17:14:18 passcore: System.ArgumentNullException: Value cannot be null.
Feb 14 17:14:18 passcore: Parameter name: input
Feb 14 17:14:18 passcore: at System.Text.RegularExpressions.Regex.Match(String input)
Feb 14 17:14:18 passcore: at System.Text.RegularExpressions.Regex.Match(String input, String pattern)
Feb 14 17:14:18 passcore: at Zyborg.PassCore.PasswordProvider.LDAP.LdapPasswordChangeProvider.ParseLdapException(LdapException ex) in C:\Unosquare\passcore\src\Zyborg.PassCore.PasswordProvider.LDAP\LdapPasswordChangeProvider.cs:line 177
Feb 14 17:14:18 passcore: at Zyborg.PassCore.PasswordProvider.LDAP.LdapPasswordChangeProvider.PerformPasswordChange(String username, String currentPassword, String newPassword) in C:\Unosquare\passcore\src\Zyborg.PassCore.PasswordProvider.LDAP\LdapPasswordChangeProvider.cs:line 125
Feb 14 17:14:18 passcore: at Unosquare.PassCore.Web.Controllers.PasswordController.Post(ChangePasswordModel model) in C:\Unosquare\passcore\src\Unosquare.PassCore.Web\Controllers\PasswordController.cs:line 93
Feb 14 17:14:18 passcore: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
Feb 14 17:14:18 passcore: Executed action method Unosquare.PassCore.Web.Controllers.PasswordController.Post (Unosquare.PassCore.Web), returned result Microsoft.AspNetCore.Mvc.BadRequestObjectResult in 1022.5591ms.
Feb 14 17:14:18 passcore: #033[40m#033[37mdbug#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector[11]
Feb 14 17:14:18 passcore: List of registered output formatters, in the following order: Microsoft.AspNetCore.Mvc.Formatters.HttpNoContentOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StringOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StreamOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter
Feb 14 17:14:18 passcore: #033[40m#033[37mdbug#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector[4]
Feb 14 17:14:18 passcore: No information found on request to perform content negotiation.
Feb 14 17:14:18 passcore: #033[40m#033[37mdbug#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector[8]
Feb 14 17:14:18 passcore: Attempting to select an output formatter without using a content type as no explicit content types were specified for the response.
Feb 14 17:14:18 passcore: #033[40m#033[37mdbug#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector[10]
Feb 14 17:14:18 passcore: Attempting to select the first formatter in the output formatters list which can write the result.
Feb 14 17:14:18 passcore: #033[40m#033[37mdbug#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector[2]
Feb 14 17:14:18 passcore: Selected output formatter 'Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter' and content type 'application/json' to write the response.
Feb 14 17:14:18 passcore: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor[1]
Feb 14 17:14:18 passcore: Executing ObjectResult, writing value of type 'Unosquare.PassCore.Web.Models.ApiResult'.
Feb 14 17:14:18 passcore: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
Feb 14 17:14:18 passcore: Executed action Unosquare.PassCore.Web.Controllers.PasswordController.Post (Unosquare.PassCore.Web) in 1027.7443ms
Feb 14 17:14:18 passcore: #033[40m#033[37mdbug#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Server.Kestrel[9]
Feb 14 17:14:18 passcore: Connection id "0HLKIISP52N9R" completed keep alive response.
Feb 14 17:14:18 passcore: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
Feb 14 17:14:18 passcore: Request finished in 1030.8002ms 400 application/json; charset=utf-8
Feb 14 17:14:24 passcore: #033[40m#033[37mdbug#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[6]
Feb 14 17:14:24 passcore: Connection id "0HLKIISP52N9R" received FIN.
Feb 14 17:14:24 passcore: #033[40m#033[37mdbug#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[7]
Feb 14 17:14:24 passcore: Connection id "0HLKIISP52N9R" sending FIN because: "The client closed the connection."
Feb 14 17:14:24 passcore: #033[40m#033[37mdbug#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Server.Kestrel[10]
Feb 14 17:14:24 passcore: Connection id "0HLKIISP52N9R" disconnecting.
Feb 14 17:14:24 passcore: #033[40m#033[37mdbug#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Server.Kestrel[2]
Feb 14 17:14:24 passcore: Connection id "0HLKIISP52N9R" stopped.

**Comment by geoperez** [comment]
The issue `Value cannot be null. Parameter name: input` is because of a null reference in the LDAP exception message. The LDAP Connection (from the Novell Library) is not returning a reason why the connection fails.

We addressed the null reference to throwing a generic LDAP exception, but this is not enough. Since we don't have an environment to reproduce this issue, we are not able to provide a solution. You can try to debug using your environment and get a better understanding of the issue. If you get any solution, let us know.

**Comment by coofercat** [comment]
FWIW, I've played about with this a fair bit over the last couple of days, against an AWS Directory Services Microsoft AD service.

In my setup, I couldn't get it to work on port 636 at all. Instead, I'm using 389 with Start TLS. This seems to work, and the AD LDAP will change passwords.

**Comment by Tomthi** [comment]
I'm tying to do the same thing using AWS Directory Services, but I'm still getting the Error Code53. What I understand it to be the action can't be completed because it's not a secure connection. It's requiring LDAPs. You can't update your PW over a non-secure connection. 

When I set the flag to StartTLS I get:
 - comment: Error initializing SSL/TLS

In AWS documentation you will need to stand up a Cert server if you want to use LDAPs. 
@coofercat Sounds like you didn't have to do this, is that correct?

Thanks.

**Comment by coofercat** [comment]
Yes, I did have to get a cert server up first. If you fancy running 2 windows servers for ever and a day, then it's an easy process, but if you want to use an offline (openssl) root CA, things get a bit more funky. Either way, it's the only way to get a cert into Directory Services. Hopefully one day, Amazon will give you an "upload cert" box instead, but until then, you're stuck with the server method.
